#!/bin/bash

# Use playerctl with the --follow option to continuously print metadata changes
playerctl metadata -F -f "{{artist}}, {{title}}, {{mpris:artUrl}}" | while read -r line; do
    artist=$(echo $line | awk -F, '{print $1}')
    song=$(echo $line | awk -F, '{print $2}')
    artUrl=$(echo $line | awk -F, '{print $3}')

    # if artist is empty echo nothing
    if [ -z "$artist" ]; then
        echo ""
    else
        # else echo json
        echo "{\"artist\":\"$artist\",\"song\":\"$song\",\"artUrl\":\"$artUrl\"}"
    fi
done
